odin:
  domain: "root@odin.websages.com"
  deploy_to: "/opt/www/tumble.wcyd.org"
  repository: "gitosis@odin.websages.com:tumble.wcyd.org.git"
  branch: "master"
freyr:
  domain: "root@freyr.websages.com"
  deploy_to: "/opt/www/tumble.wcyd.org"
  repository: "gitosis@freyr.websages.com:tumble.wcyd.org.git"
  branch: "master"
thor:
  domain: "root@thor.websages.com"
  deploy_to: "/opt/www/tumble.wcyd.org"
  repository: "gitosis@odin.websages.com:tumble.wcyd.org.git"
  branch: "master"
